### ISSUE TITLE
レシピ提供機能について

### ISSUE THREAD

**Issue by sakamoto-kohei-44** [sakamoto-kohei-44/GainMate#114]
レシピ提供機能に関して悩んでいる部分があるのでアドバイス頂きたく思います。
現在、READMEにあるようにspoonacular apiを使用し、ユーザーに沿った適切なカロリーのレシピを取得出来るように実装しました。
しかし、海外のAPIなのでほとんどが海外料理で私生活で日本人が作るようなレシピはあまり取得出来ませんでした。
楽天レシピAPIや他のAPIを検討しましたが、楽天レシピではカロリーや栄養情報がレスポンスに含まれていないためフィルタリング出来ず、他の無料で使用出来そうなAPIも見つかりませんでした。
API検証の際は、期待したレスポンスが返ってくることだけ確認したため、どのような画像や料理なのか深く考えていませんでした。
また、レシピ提供がメインの機能なのでアプリとしてあまり成り立たないような気がして来ました。

自分でデータベースを作り、カロリー範囲ごとにあらかじめ楽天レシピAPIからレシピを複数追加しておいて、ランダムで表示するなども考えましたが、料理ごとに固有のIDを持っていなかったので、この実装方法も出来なさそうです。

ChatGPTのAPIを使い、画像は表示出来ませんが文面だけレシピを表示する、適切な細かいカロリー範囲指定は出来ませんが、カロリーの高そうな食材のカテゴリからレシピを表示させ誤魔化すなども考えましたが、イマイチピンと来ません。

もし無理そうなら、その分UI.UXに力を入れる。
もしくは、出来るだけ今の機能のまま少しコンセプトを変えるなどを考えています。
また、一か八か、レシピ検索サイト みんなのきょうの料理が提供しているAPIを無料で個人開発で利用出来るか問い合わせ中です。
最終的には個人の判断になるとは思いますが、このようなやり方があるなど何かしらアドバイス頂けるとありがたいです。。

**Comment by Tsuchiya2** [comment]
> 多くの人が体重を落としたいと考える現代社会ですが、体重を増やしたいと感じている人も多く存在します。
特に、食事の量や質に挑戦している人、体質的に太りにくいと感じている人が、ただ増量を目的とした食事を取るだけでは十分な結果を得ることはなかなか難しいです。
栄養バランス、カロリー摂取量、食事のタイミングや頻度など、体重を増やすための効果的なアプローチには幅広い知識が求められます。
そこで、標準体重に近づきたい人や細マッチョを目指す人向けに、食事に特化した情報とサポートを提供するサービスを提案します。
売りや差別化のポイントとしては
・ほとんどの健康・食事アプリは減量をメインにしていますが、このサービスは増量を目指す人に特化している点が最大の売りです。
・ユーザーの体質、目標に応じてカスタマイズされた食事プランのアドバイスを提供することで、一人ひとりのニーズに合わせたサポートを実現します。
・メニュー作成時に、自分の苦手な食材と好きな食材を指定することでユーザーが嫌いな食材を避けながら、それでもバランスの取れた食事プランを提案する。これにより、食事を続けるモチベーションを維持しやすくします。
・単に食事プランを提供するだけでなく、なぜその食材やタイミングが推奨されるのかの理由や背景も提供します。これにより、ユーザーは増量の知識を深めることができ、自分自身での食事選びの基準も養うことができます。
・競合サービスとの差別化ポイントとして、いくつかの献立アプリでは、主に食材を指定して一週間分のレシピをAIが自動生成する機能がメインですが、カロリー管理や増量を目的としたレシピの生成機能はありません。
一方、筋トレアプリではカロリー管理や体重管理をグラフ等で視覚化する機能は備えていますが、増量のための適切なレシピを生成する機能はありません。
このアプリでは、カロリー管理や体重管理をグラフなどで視覚化する機能と、増量のための適切なレシピを生成する機能の両方を組み合わせることで、二つのアプリの長所を取り入れた形となっており、これが最大の差別化ポイントです。

上記に対してサービスの変更が必要なら再READMEレビューを依頼してください。

海外のレシピしか返ってこないようであれば、それをChatGPTに投げて日本料理・中華etcで近いものだとどんな料理になるのか投げてみると何か返してくれるかもしれません。いろいろ試してみてください。

**Comment by sakamoto-kohei-44** [comment]
ありがとうございます！
試しにGPTに投げてみると似たような日本料理に変換してくれました！色々と組み合わせるとまた面白い機能になる気がしました！
アドバイスありがとうございます🙇‍♀️
